# Generated by Django 4.0.3 on 2022-04-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_brand_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
